kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: veo
  name: "{{ .Values.storageClass }}"
  {{- if .Values.defaultClass }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: "{{ .Values.provisionerName }}"
parameters:
  mountOptions: "vers=4.1"
