kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: "{{ .Values.storageClass }}"
  {{- if .Values.defaultClass }}
  namespace: veo
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: "{{ .Values.provisionerName }}"
